### ISSUE TITLE
Csproj

### ISSUE THREAD

**Issue by jerone** [sandercox/AutoSortVcxprojFilters#1]
Could this extension be extended with `.csproj` project files?

**Comment by sandercox** [comment]
I guess it could be added somewhat similar but there is a big difference that the .filters file for c++ is not the actual project...

Also we've noticed quite a few issues with git-rebase and VS open at the same time causing issues with the filters file so we no longer have this extension active anymore.

**Comment by jerone** [comment]
Ok, "bedankt" for letting me know. I might use this code as a base for my own extension; it looks great.
