### ISSUE TITLE
"The 'AutoSortPackage' package did not load correctly." warning when opening VS

### ISSUE THREAD

**Issue by GaineyRoy** [sandercox/AutoSortVcxprojFilters#3]
### Installed product versions
- Visual Studio: 2017 Professional, version 15.8
- This extension: 1.0.12

### Description
A warning appears when opening Visual Studio with the my last solution. The warning mentions that the package didn't load correctly but the extensions works as expected.

### Steps to recreate
1. Opens Visual Studio
2. Opens a project 
3. Waits a couple of second and you should get the following warning :

![image](https://user-images.githubusercontent.com/36120481/63946728-9b61ac80-ca43-11e9-995a-2fff1f48214d.png)

Here's the content of the log file as mention in the previous screenshot :

  <entry>
    <record>658</record>
    <time>2019/08/29 13:58:41.432</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [AutoSortPackage]</description>
    <guid>{01A71080-33CD-4769-883B-07242C7C6C3E}</guid>
  </entry>
  <entry>
    <record>659</record>
    <time>2019/08/29 13:58:41.443</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [AutoSortPackage]Source: &apos;Microsoft.VisualStudio.Shell.14.0&apos; Description: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.&#x000D;&#x000A;System.InvalidOperationException: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(Type serviceType)&#x000D;&#x000A;   at System.ComponentModel.Design.MenuCommandService.GetService(Type serviceType)&#x000D;&#x000A;   at System.ComponentModel.Design.MenuCommandService.EnsureVerbs()&#x000D;&#x000A;   at System.ComponentModel.Design.MenuCommandService.FindCommand(Guid guid, Int32 id)&#x000D;&#x000A;   at System.ComponentModel.Design.MenuCommandService.FindCommand(CommandID commandID)&#x000D;&#x000A;   at System.ComponentModel.Design.MenuCommandService.AddCommand(MenuCommand command)&#x000D;&#x000A;   at AutoSortVcxprojFilters.SortAllCommand..ctor(Package package) in C:\projects\autosortvcxprojfilters\AutoSortVcxprojFilters\SortAllCommand.cs:line 52&#x000D;&#x000A;   at AutoSortVcxprojFilters.AutoSortPackage.&lt;InitializeAsync&gt;d__4.MoveNext() in C:\projects\autosortvcxprojfilters\AutoSortVcxprojFilters\AutoSortPackage.cs:line 87&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass16_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()</description>
    <guid>{01A71080-33CD-4769-883B-07242C7C6C3E}</guid>
    <hr>80131509</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>660</record>
    <time>2019/08/29 13:58:41.445</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [AutoSortPackage]</description>
    <guid>{01A71080-33CD-4769-883B-07242C7C6C3E}</guid>
    <hr>80131509</hr>
    <errorinfo></errorinfo>
  </entry>

### Current behavior
A warning is shown each time I open my first project in Visual Studio.

### Expected behavior
I would expect the extension to work without any warning in Visual Studio.

**Comment by sandercox** [comment]
Fixed.
